AuctionsTable:
  Type: AWS::DynamoDB::Table
  Properties: 
    # In order to make it more flexible, it gets the name of the table + current env
    TableName: AuctionsTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH